name: Build

on:
  push:
    paths:
      - '**/*'
      - '!README.md'
      - '!LICENSE'
      - '!**/.gitignore'
  pull_request:
    paths:
      - '**/*'
      - '!README.md'
      - 'LICENSE'
      - '!**/.gitignore'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc
      - name: Build for x86
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Build for ARM
        run: cargo build --release --target aarch64-pc-windows-msvc
      - name: Prepare saving build
        run: |
            mkdir -p target/build
            mv "target/x86_64-pc-windows-msvc/release/${{ github.repository | lower }}.exe" "target/build/${{ github.repository }} (${{ runner.os }} x86).exe"
            mv "target/aarch64-pc-windows-msvc/release/${{ github.repository | lower }}.exe" "target/build/${{ github.repository }} (${{ runner.os }} ARM).exe"
      - name: Save build
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin, aarch64-apple-darwin
      - name: Build for x86
        run: cargo build --release --target x86_64-apple-darwin
      - name: Build for ARM
        run: cargo build --release --target aarch64-apple-darwin
      - name: Prepare saving build
        run: |
            mkdir -p target/build
            mv "target/x86_64-apple-darwin/release/${{ github.repository | lower }}" "target/build/${{ github.repository }} (${{ runner.os }} x86)"
            mv "target/aarch64-apple-darwin/release/${{ github.repository | lower }}" "target/build/${{ github.repository }} (${{ runner.os }} ARM)"
      - name: Save build
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build for x86
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Prepare saving build
        run: |
            mkdir -p target/build
            mv "target/x86_64-unknown-linux-gnu/release/${{ github.repository | lower }}" "target/build/${{ github.repository }} (${{ runner.os }} x86)"
      - name: Save build
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build
