name: Download Cache

on:
  push:
    branches:
      - main # Ändere dies entsprechend deinem Branch-Namen

jobs:
  download_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Cache linux
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build-Linux
      - name: Download Cache Windows
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build-Windows
      - name: Download Cache macOS
        uses: actions/cache@v3
        with:
          path: target/build
          key: Build-Windows